/**
 * DEVSIGHTAI — Terms & Conditions
 *
 * Operational conditions, acceptable telemetry use, automated action boundaries,
 * and service availability disclaimers for the DEVSIGHTAI platform.
 */

import { Link } from 'react-router-dom'
import { IconTerms, IconAlertTriangle, IconActivity, IconCpu } from '../components/icons'

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-4">
      {/* Header */}
      <div className="border-b border-border-default pb-5">
        <div className="flex items-center gap-2 text-accent-blue mb-2 text-xs font-mono font-semibold uppercase tracking-wider">
          <IconTerms className="w-4 h-4" />
          <span>Platform Terms of Use</span>
        </div>
        <h1 className="text-2xl font-bold text-text-primary">
          Terms & Conditions
        </h1>
        <p className="text-sm text-text-muted mt-1">
          Effective Date: September 2026 • Platform Version 1.0
        </p>
      </div>

      {/* Overview Card */}
      <div className="p-5 rounded-xl border border-border-default bg-bg-card space-y-3">
        <h2 className="text-base font-bold text-text-primary">
          1. Acceptance of Terms
        </h2>
        <p className="text-sm text-text-secondary leading-relaxed">
          By accessing or deploying the DEVSIGHTAI reliability monitoring platform, integrating its collection agents, or utilizing its AI root-cause analysis and remediation capabilities, you agree to comply with these terms. If you are using the platform on behalf of an enterprise entity, you confirm authorization to bind that organization to these terms.
        </p>
      </div>

      {/* Core Rules Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-5 rounded-xl border border-border-default bg-bg-card space-y-3">
          <div className="flex items-center gap-2 text-accent-green font-bold text-sm">
            <IconActivity className="w-4 h-4" />
            <h3>2. Authorized Telemetry Ingestion</h3>
          </div>
          <p className="text-xs text-text-secondary leading-relaxed">
            Users may only ingest metrics, traces, and system logs from infrastructure and applications they own or operate. Ingestion of raw unscrubbed credentials, credit card numbers, or proprietary consumer secrets into log pipelines is strictly prohibited by platform policy.
          </p>
        </div>

        <div className="p-5 rounded-xl border border-border-default bg-bg-card space-y-3">
          <div className="flex items-center gap-2 text-accent-blue font-bold text-sm">
            <IconCpu className="w-4 h-4" />
            <h3>3. AI Advisory Nature</h3>
          </div>
          <p className="text-xs text-text-secondary leading-relaxed">
            Automated Root Cause Analyses (RCA), predictive failure warnings, and suggested runbooks generated by DEVSIGHTAI's Groq Llama-3.3-70B pipeline serve as diagnostic recommendations. Engineering teams maintain ultimate responsibility for evaluating and executing remediation commands in production.
          </p>
        </div>
      </div>

      {/* Remediation & Automated Controls */}
      <div className="p-5 rounded-xl border border-border-default bg-bg-card space-y-3">
        <div className="flex items-center gap-2 text-amber-500 font-bold text-sm">
          <IconAlertTriangle className="w-4 h-4" />
          <h2 className="text-base font-bold text-text-primary">
            4. Automated Remediation & Production Controls
          </h2>
        </div>
        <p className="text-sm text-text-secondary leading-relaxed">
          Actions executed via the platform—such as Kubernetes rollbacks, pod restarts, auto-scaling commands, or connection pool resets—execute directly against configured service endpoints. Users are responsible for verifying that role permissions (Developer, DevOps, QA, Manager) are appropriately audited and scoped to avoid inadvertent production disruption.
        </p>
      </div>

      {/* Availability Disclaimer */}
      <div className="p-5 rounded-xl border border-border-default bg-bg-card space-y-3">
        <h2 className="text-base font-bold text-text-primary">
          5. Availability & Service Targets
        </h2>
        <p className="text-sm text-text-secondary leading-relaxed">
          While DEVSIGHTAI tracks SLA and SLO metrics for your connected services, the platform itself is provided on an "as is" and "as available" basis. Target availability metrics displayed within the platform represent real-time computations derived from client-provided telemetry datasets.
        </p>
      </div>

      {/* Footer */}
      <div className="pt-4 border-t border-border-default flex flex-col sm:flex-row items-center justify-between text-xs text-text-muted gap-2">
        <p>Inquiries: <span className="font-mono text-text-secondary">legal@devsight.ai</span></p>
        <Link to="/" className="text-accent-blue hover:underline font-medium">
          ← Return to Dashboard
        </Link>
      </div>
    </div>
  )
}
